image: r-base

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - r-packages

before_script:
  - R -e "install.packages(c('testthat', 'roxygen2', 'remotes', 'pkgbuild', 'pkgload', 'rcmdcheck', 'revdepcheck', 'sessioninfo', 'usethis', 'pkgdown', 'urlchecker'), repos = 'http://cran.rstudio.com/')"
  - R -e "install.packages('devtools', repos = 'http://cran.rstudio.com/')"
  - R -e ".libPaths('r-packages')"

test:
  script:
    - Rscript -e "devtools::test()"
  only:
    - main
