image: r-base

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - r-packages

before_script:
  - apt-get update -qq && apt-get install -y libssl-dev libcurl4-openssl-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
  - R -e "install.packages(c('testthat', 'roxygen2', 'remotes', 'pkgbuild', 'pkgload', 'rcmdcheck', 'revdepcheck', 'sessioninfo', 'usethis', 'pkgdown', 'urlchecker'), repos = 'http://cran.rstudio.com/')"
  - R -e "install.packages('devtools', repos = 'http://cran.rstudio.com/')"
  - R -e "install.packages(c('ape', 'coda', 'lubridate'), repos = 'http://cran.rstudio.com/')"
  - R -e ".libPaths('r-packages')"

test:
  script:
    - Rscript -e "devtools::test()"
  only:
    - main
